#!/usr/bin/env bash
set -e

database_path=${SPRING_DATASOURCE_URL##*/}
database_name=${database_path%%\?*}

mysql -e "create database $database_name;"
mysql -e "create user '$SPRING_DATASOURCE_USERNAME'@'localhost' identified by '$SPRING_DATASOURCE_PASSWORD';"
mysql -e "grant all privileges on $database_name.* to '$SPRING_DATASOURCE_USERNAME'@'localhost';"
mysql -e "flush privileges;"

# References

# Setup MySQL database w/ a Bash script: https://stackoverflow.com/a/33474729/2675670
# Parsing a URL: https://stackoverflow.com/a/5497428/2675670
