#!/bin/bash
set -e

database_path=${SPRING_DATASOURCE_URL##*/}
database_name=${database_path%%\?*}

mysql -e "show databases like '$database_name';"
mysql -e "select host, user from mysql.user where user like '$SPRING_DATASOURCE_USERNAME';"
mysql -e "show grants for '$SPRING_DATASOURCE_USERNAME'@'localhost';"
