#!/usr/bin/env bash
set -e

database_path=${SPRING_DATASOURCE_URL##*/}
database_name=${database_path%%\?*}
schema_path="./src/main/resources/db"
filename="$schema_path/schema.sql"

mysqldump --no-data "$database_name" > "$filename"
